version: '2'

services:

  app:
    build: './app'
    command: npm start
    ports:
      - '80:3000'
    env_file: .env
    volumes:
      - ./app:/home/app/server
      - /home/app/server/node_modules

  mongo:
    build: './mongo'
    ports:
      - '27017'
    volumes:
      - /opt/mongodb:/data/db

  api:
    build: './api'
    command: npm start
    ports:
      - '5000'
    env_file: .env
    volumes:
      - ./api:/home/api/server
      - /home/app/server/node_modules
    depends_on:
      - mongo
