version: '2'

services:

  app:
    build: './app'
    command: npm start
    ports:
      - '443:3000'
      - '80:3000'
    env_file: .env
    volumes:
      - ./app:/home/app/server
      - /home/app/server/node_modules
      - /etc/letsencrypt:/home/app/server/certs

  mongo:
    build: './mongo'
    ports:
      - '27017'
    volumes:
      - ./mongodb:/data/db

  api:
    build: './api'
    command: npm start
    ports:
      - '5000'
    env_file: .env
    volumes:
      - ./api:/home/api/server
      - /home/api/server/node_modules
    depends_on:
      - mongo
