version: '2'

services:

  certs:
    image: centurylink/openssl
    environment:
      COMMON_NAME: portefoliodev
      KEY_NAME: portefoliodev
    volumes:
      - certs:/certs

  app:
    build: './app'
    command: yarn run dev
    environment:
      APPHTTPSPORT: 8080
      APPHTTPPORT: 3000
      APIHOST: api
      APIPORT: 5000
    env_file: .env
    ports:
      - '3000:3000'
      - '3001:3001'
      - '8080:8080'
    depends_on:
      - certs
    volumes:
      - ./app:/home/app/server
      - /home/app/server/node_modules
      - certs:/home/app/server/certs

  api:
    build: './api'
    command: yarn run dev
    environment:
      APIPORT: 5000
    env_file: .env
    ports:
      - '5000:5000'
    volumes:
      - ./api:/home/api/server
      - /home/api/server/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '5050:27017'

volumes:
  certs: {}
