version: '2'

services:

  app:
    build: './app'
    command: npm start
    ports:
      - '80:3000'
    env_file: .env
    volumes:
      - ./app:/home/app/server
      - app-deps:/home/app/server/node_modules

  mongo:
    image: mongo
    ports:
      - '27017'
    volumes:
      - ./data:/data/db

  api:
    build: './api'
    command: npm start
    ports:
      - '5000'
    env_file: .env
    volumes:
      - ./api:/home/api/server
      - api-deps:/home/api/server/node_modules
      - /etc/letsencrypt
    depends_on:
      - mongo


# empty volumes for api and app node_modules
volumes:
  app-deps:
  api-deps:
