version: '2'
services:

  api:
    build: './api'
    command: npm run dev
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./api:/home/api/server
      - /home/api/server/node_modules

  app:
    build: './app'
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      DOCKER: "true"
    volumes:
      - ./app:/home/app/server
      - /home/app/server/node_modules

  mongo:
    image: mongo
    ports:
      - "27017:27017"
