version: '2'
services:

  app:
    build: './app'
    command: npm run dev --silent
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      APIHOST: 'api'
      APIPORT: 5000
    volumes:
      - ./app:/home/app/server
      - /home/app/server/node_modules

  api:
    build: './api'
    command: npm run dev --silent
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      DATABASE: 'mongodb://mongo/portefolio'
      SECRET: 'secrettoken'
      REGISTRATIONSECRET: 'secrettoken'
    volumes:
      - ./api:/home/api/server
      - /home/api/server/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '5050:27017'
