// Auth
export const LOAD_AUTH = 'LOAD_AUTH'
export const LOAD_AUTH_SUCCESS = 'LOAD_AUTH_SUCCESS'
export const LOAD_AUTH_FAIL = 'LOAD_AUTH_FAIL'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

// Posts & Drafts
export const LOAD_POSTS_AND_DRAFTS = 'LOAD_POSTS_AND_DRAFTS'
export const LOAD_POSTS_AND_DRAFTS_SUCCESS = 'LOAD_POSTS_AND_DRAFTS_SUCCESS'
export const LOAD_POSTS_AND_DRAFTS_FAIL = 'LOAD_POSTS_AND_DRAFTS_FAIL'

export const LOAD_POSTS = 'LOAD_POSTS'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL'

export const UPDATE_POST = 'UPDATE_POST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const PUBLISH = 'PUBLISH'
export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS'
export const PUBLISH_FAIL = 'PUBLISH_FAIL'

export const UNPUBLISH = 'UNPUBLISH'
export const UNPUBLISH_SUCCESS = 'UNPUBLISH_SUCCESS'
export const UNPUBLISH_FAIL = 'UNPUBLISH_FAIL'

export const CREATE_ACTIVE_DRAFT = 'CREATE_ACTIVE_DRAFT'
export const UPDATE_ACTIVE_DRAFT = 'UPDATE_ACTIVE_DRAFT'

export const LOAD_DRAFTS = 'LOAD_DRAFTS'
export const LOAD_DRAFTS_SUCCESS = 'LOAD_DRAFTS_SUCCESS'
export const LOAD_DRAFTS_FAIL = 'LOAD_DRAFTS_FAIL'

export const SAVE_DRAFT = 'SAVE_DRAFT'
export const SAVE_DRAFT_SUCCESS = 'SAVE_DRAFT_SUCCESS'
export const SAVE_DRAFT_FAIL = 'SAVE_DRAFT_FAIL'

export const UPDATE_DRAFT = 'UPDATE_DRAFT'
export const UPDATE_DRAFT_SUCCESS = 'UPDATE_DRAFT_SUCCESS'
export const UPDATE_DRAFT_FAIL = 'UPDATE_DRAFT_FAIL'

export const DELETE_DRAFT = 'DELETE_DRAFT'
export const DELETE_DRAFT_SUCCESS = 'DELETE_DRAFT_SUCCESS'
export const DELETE_DRAFT_FAIL = 'DELETE_DRAFT_FAIL'

// Messages
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const DISSMISS_MESSAGE = 'DISSMISS_MESSAGE'

// Ui

// Editor
export const SWITCH_VIEW = 'SWITCH_VIEW'
export const TOGGLE_EDITOR_DROPDOWN = 'TOGGLE_EDITOR_DROPDOWN'
export const TOGGLE_EDITOR_NAV = 'TOGGLE_EDITOR_NAV'
export const TOGGLE_EDITOR_SETTINGS = 'TOGGLE_EDITOR_SETTINGS'

// Nav
export const TOGGLE_NAV = 'TOGGLE_NAV'
