// Auth
export const LOAD_AUTH = 'LOAD_AUTH'
export const LOAD_AUTH_SUCCESS = 'LOAD_AUTH_SUCCESS'
export const LOAD_AUTH_FAIL = 'LOAD_AUTH_FAIL'
export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

// Posts
export const LOAD_POSTS = 'LOAD_POSTS'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL'
export const CREATE_DRAFT = 'CREATE_DRAFT'
export const UPDATE_DRAFT = 'UPDATE_DRAFT'
export const PUBLISH_DRAFT = 'PUBLISH_DRAFT'
export const PUBLISH_DRAFT_SUCCESS = 'PUBLISH_DRAFT_SUCCESS'
export const PUBLISH_DRAFT_FAIL = 'PUBLISH_DRAFT_FAIL'

export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const HIDE_MESSAGE = 'HIDE_MESSAGE'
