// Auth
export const LOAD_AUTH = 'LOAD_AUTH'
export const LOAD_AUTH_SUCCESS = 'LOAD_AUTH_SUCCESS'
export const LOAD_AUTH_FAIL = 'LOAD_AUTH_FAIL'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

// Posts & Drafts
export const LOAD_POSTS = 'LOAD_POSTS'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL'

export const EDIT_POST = 'EDIT_POST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const PUBLISH = 'PUBLISH'
export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS'
export const PUBLISH_FAIL = 'UNPUBLISH_FAIL'

export const UNPUBLISH = 'UNPUBLISH'
export const UNPUBLISH_SUCCESS = 'UNPUBLISH_SUCCESS'
export const UNPUBLISH_FAIL = 'UNPUBLISH_FAIL'

export const CREATE_DRAFT = 'CREATE_DRAFT'
export const UPDATE_DRAFT = 'UPDATE_DRAFT'

export const LOAD_DRAFTS = 'LOAD_DRAFTS'
export const LOAD_DRAFTS_SUCCESS = 'LOAD_DRAFTS_SUCCESS'
export const LOAD_DRAFTS_FAIL = 'LOAD_DRAFTS_FAIL'

export const SAVE_DRAFTS = 'SAVE_DRAFTS'
export const SAVE_DRAFTS_SUCCESS = 'SAVE_DRAFTS_SUCCESS'
export const SAVE_DRAFTS_FAIL = 'SAVE_DRAFTS_FAIL'

export const DELETE_DRAFTS = 'DELETE_DRAFTS'
export const DELETE_DRAFTS_SUCCESS = 'DELETE_DRAFTS_SUCCESS'
export const DELETE_DRAFTS_FAIL = 'DELETE_DRAFTS_FAIL'

// Messages
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const DISSMISS_MESSAGE = 'DISSMISS_MESSAGE'
